name: gur
description: This application allows the users to donate food to local NGOs, who will transport it to the needy persons.
  You need to select the amount of food and give remarks, if any, to the NGO that will be coming to take the delivery.
  The application will automatically detect your location and list the NGOs near you.
  You can select any NGO of your choice(affected by your previous experience or fame of NGOs).
  You can also have an in-app chat conversation with the person who will be coming up, if there is any change in plan, or they need to come delayed, or early.
  You'll get a prompt for your packet request and will get a message as soon as the NGO accepts/rejects it.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bubble: ^1.1.9+1
  cached_network_image: ^2.5.1
  carousel_slider: ^3.0.0
  cloud_firestore: ^1.0.1
  cloud_functions: ^1.0.1
  cupertino_icons: ^1.0.0
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.2
  firebase_messaging: ^9.0.1
  firebase_storage: ^8.0.0
  flutter_animated_dialog: ^2.0.0
  flutter_email_sender: ^4.0.0
  flutter_local_notifications: ^5.0.0
  flutter_native_splash: ^1.1.5+1
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_switch: ^0.2.2
  geolocator: ^7.0.1
  google_fonts: ^2.0.0
  image_picker: ^0.7.3
  location: ">=1.0.0 <=4.0.0"
  material_design_icons_flutter: null
  otp_text_field: ^1.1.0
  shared_preferences: ^2.0.5
  toast: null
  url_launcher: ^6.0.2
  page_transition: "^1.1.7+6"
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#FFFFFF"
  image: images/splash2.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - images/