name: gur
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bubble: ^1.1.9+1
  cached_network_image: ^2.5.1
  carousel_slider: ^3.0.0
  cloud_firestore: ^1.0.1
  cloud_functions: ^1.0.1
  cupertino_icons: ^1.0.0
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.2
  firebase_messaging: ^9.0.1
  firebase_storage: ^8.0.0
  flutter_animated_dialog: ^2.0.0
  flutter_email_sender: ^4.0.0
  flutter_local_notifications: ^5.0.0
  flutter_native_splash: ^1.1.5+1
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_switch: ^0.2.2
  geolocator: ^7.0.1
  google_fonts: ^2.0.0
  image_picker: ^0.7.3
  location: ">=1.0.0 <=4.0.0"
  material_design_icons_flutter: null
  otp_text_field: ^1.1.0
  shared_preferences: ^2.0.5
  titled_navigation_bar: ^4.1.0
  toast: null
  url_launcher: ^6.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#000000"
  image: images/splash.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
